version: '3.3'
services:

  app: &app_base
    build:
      context: .
    env_file:
      - "${ENV_FILE}"
    ports:
      - "80:4000"

  worker:
    <<: *app_base
    command: bin/workers
    ports: []
