UPDATE city SET otherNames = 'Alexandria, Rio Grande do Norte;' WHERE id = 7128;
UPDATE city SET otherNames = 'Alta Floresta d\'Oeste;' WHERE id = 7312;
UPDATE city SET otherNames = 'Amparo do Serra;' WHERE id = 2673;
UPDATE city SET otherNames = 'Arês;' WHERE id = 7135;
UPDATE city SET otherNames = 'Assu;' WHERE id = 7125;
UPDATE city SET otherNames = 'Bataiporã;' WHERE id = 4125;
UPDATE city SET otherNames = 'Belém de São Francisco;' WHERE id = 5168;
UPDATE city SET otherNames = 'Campos dos Goitacazes;' WHERE id = 6881;
UPDATE city SET otherNames = 'Chiapeta;' WHERE id = 7587;
UPDATE city SET otherNames = 'Dias d\'Ávila;' WHERE id = 565;
UPDATE city SET otherNames = 'Dona Eusébia;' WHERE id = 3059;
UPDATE city SET otherNames = 'Embu das Artes;' WHERE id = 9113;
UPDATE city SET otherNames = 'Espigão d\'Oeste;' WHERE id = 7330;
UPDATE city SET otherNames = 'Espigão d\'Oeste;' WHERE id = 7330;
UPDATE city SET otherNames = 'Espírito Santo (Londrina);' WHERE id = 6053;
UPDATE city SET otherNames = 'Estrela d\'Oeste;' WHERE id = 9127;
UPDATE city SET otherNames = 'Euclides da Cunha, Bahia;' WHERE id = 578;
UPDATE city SET otherNames = 'Gouveia;' WHERE id = 3168;
UPDATE city SET otherNames = 'Gracho Cardoso;' WHERE id = 8793;
UPDATE city SET otherNames = 'Herval d\'Oeste;' WHERE id = 8478;
UPDATE city SET otherNames = 'Itabirinha de Mantena;' WHERE id = 3235;
UPDATE city SET otherNames = 'Itamaracá;' WHERE id = 5293;
UPDATE city SET otherNames = 'Itapagé;' WHERE id = 1419;
UPDATE city SET otherNames = 'Itaporanga d\'Ajuda;' WHERE id = 8799;
UPDATE city SET otherNames = 'Jiquiriçá;' WHERE id = 750;
UPDATE city SET otherNames = 'João Câmara, Rio Grande do Norte;' WHERE id = 7194;
UPDATE city SET otherNames = 'Lagoa de Itaenga;' WHERE id = 5322;
UPDATE city SET otherNames = 'Microregion of Caraguatatuba;' WHERE id = 9043;
UPDATE city SET otherNames = 'Mirassol D\'Oeste;' WHERE id = 4398;
UPDATE city SET otherNames = 'Morada Nova (Marabá);' WHERE id = 4698;
UPDATE city SET otherNames = 'Nova Brasilândia d\'Oeste;' WHERE id = 7342;
UPDATE city SET otherNames = 'Olho d\'Água das Flores;' WHERE id = 127;
UPDATE city SET otherNames = 'Olho-d\'Água do Borges;' WHERE id = 7224;
UPDATE city SET otherNames = 'Paraíso das Águas;' WHERE id = 4219;
UPDATE city SET otherNames = 'Paraty;' WHERE id = 7004;
UPDATE city SET otherNames = 'Pedra Branca do Amapari;' WHERE id = 281;
UPDATE city SET otherNames = 'Piçarras;' WHERE id = 4738;
UPDATE city SET otherNames = 'Pindaré-Mirim;' WHERE id = 2537;
UPDATE city SET otherNames = 'Planaltina;' WHERE id = 2285;
UPDATE city SET otherNames = 'Poxoréo;' WHERE id = 4448;
UPDATE city SET otherNames = 'Quarto Centenário;' WHERE id = 6838;
UPDATE city SET otherNames = 'Queluzito;' WHERE id = 3673;
UPDATE city SET otherNames = 'Santa Bárbara D\'Oeste;' WHERE id = 9595;
UPDATE city SET otherNames = 'Santa Cruz do Monte Castelo;' WHERE id = 6572;
UPDATE city SET otherNames = 'Santa Luzia d\'Oeste;' WHERE id = 7359;
UPDATE city SET otherNames = 'Santa Teresinha;' WHERE id = 998;
UPDATE city SET otherNames = 'Santo Antonuio do Leste;' WHERE id = 10096;
UPDATE city SET otherNames = 'São Benedito (Santa Luzia);' WHERE id = 3815;
UPDATE city SET otherNames = 'São Caetano;' WHERE id = 5435;
UPDATE city SET otherNames = 'São João del-Rei;' WHERE id = 3857;
UPDATE city SET otherNames = 'São João do Pau d\'Alho;' WHERE id = 9652;
UPDATE city SET otherNames = 'São Luís do Paraitinga;' WHERE id = 9663;
UPDATE city SET otherNames = 'Senador La Rocque;' WHERE id = 2599;
UPDATE city SET otherNames = 'Taperoá, Paraíba;' WHERE id = 5120;
UPDATE city SET otherNames = 'Valente, Bahia;' WHERE id = 1103;
